USE DiscGolf
GO

CREATE TABLE Round(
	roundID int,
	courseID int,
	date DATETIME,
	temp int,
	windSpeed int,
	roundScore int,
	hole1score int,
	hole2score int,
	hole3score int,
	hole4score int,
	hole5score int,
	hole6score int,
	hole7score int,
	hole8score int,
	hole9score int,
	hole10score int,
	hole11score int,
	hole12score int,
	hole13score int,
	hole14score int,
	hole15score int,
	hole16score int,
	hole17score int,
	hole18score int,
	hole19score int,
	hole20score int,
	hole21score int,
	hole22score int,
	hole23score int,
	hole24score int,
	hole25score int,
	hole26score int,
	hole27score int,
	hole28score int,
	hole29score int,
	hole30score int,
	holeAscore int,
	holeBscore int,
	holeCscore int,
	holeDscore int,
	holeEscore int,
	holeFscore int
)