USE DiscGolf
GO

CREATE TABLE Courses(
	courseID int,
	courseName varchar(100),
	courseLayout varchar(100),
	coursePar int,
	hole1 int,
	hole2 int,
	hole3 int,
	hole4 int,
	hole5 int,
	hole6 int,
	hole7 int,
	hole8 int,
	hole9 int,
	hole10 int,
	hole11 int,
	hole12 int,
	hole13 int,
	hole14 int,
	hole15 int,
	hole16 int,
	hole17 int,
	hole18 int,
	hole19 int,
	hole20 int,
	hole21 int,
	hole22 int,
	hole23 int,
	hole24 int,
	hole25 int,
	hole26 int,
	hole27 int,
	hole28 int,
	hole29 int,
	hole30 int,
	holeA int,
	holeB int,
	holeC int,
	holeD int,
	holeE int,
	holeF int
)

--DROP TABLE DiscGolf.dbo.Courses